server:
  port: 8081
logging:
  level:
    top.yaoch: debug
    org:
      springframework:
        security: debug

security:
  oauth2:
    resource:
      tokenInfoUri: http://localhost:8080/oauth/check_token
      preferTokenInfo: true

    client:
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
      clientId: client_1
      clientSecret: 123456

