server:
  port: 8088
# 分布式文件系统FDFS配置
fdfs:
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  reqHost: 47.104.129.104   #nginx访问地址
  reqPort: 8080             #nginx访问端口
  groupName: fatych             #分组
  thumbImage: #缩略图生成参数，可选
    width: 150
    height: 150
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
    - 47.104.129.104:22122

spring:
  application:
    name: springboot-fastdfs
  servlet:
    multipart:
      max-file-size: 100MB # 最大支持文件大小
